services:
    mongo:
        build: ./
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
#            надо исправить логин и пароль
        ports:
            - 27017:27017
        mem_limit: 500m